name: Release update

on:
  release:
    types: [published]

env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  angular-demo-update-release:
    name: Angular Demo update release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set RELEASE_VERSION
        run: |
           echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - name: Install latest sdk version
        run: |
          npm install aliceonboarding@${RELEASE_VERSION}
      - name: Build angular demo
        run:  |
          npm run build
      - name: Git - Update changes
        run: |
          npm version --no-git-tag-version ${RELEASE_VERSION}
          git add -u
      - name: Git - Commit changes
        run: |
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"
          git commit -m "Update version to ${RELEASE_VERSION}"
      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}
          branch: master
